//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Customers()
        {
            this.Table_Invoice = new HashSet<Table_Invoice>();
        }
    
        public int Customer_ID { get; set; }
        public string Customer_FullName { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_PhoneNumber { get; set; }
        public string Customer_RegisterDate { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<bool> Customer_Delete { get; set; }
    
        public virtual Table_Users Table_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Invoice> Table_Invoice { get; set; }
    }
}
