//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Users()
        {
            this.Table_Customers = new HashSet<Table_Customers>();
            this.Table_Inventory = new HashSet<Table_Inventory>();
            this.Table_Invoice = new HashSet<Table_Invoice>();
            this.Table_Product = new HashSet<Table_Product>();
            this.Table_ProductPriceManagment = new HashSet<Table_ProductPriceManagment>();
            this.Table_UserLog = new HashSet<Table_UserLog>();
        }
    
        public int User_ID { get; set; }
        public string User_FirstName { get; set; }
        public string User_LastName { get; set; }
        public string User_Tel { get; set; }
        public Nullable<byte> User_Age { get; set; }
        public Nullable<bool> User_Gender { get; set; }
        public string User_Username { get; set; }
        public string User_Paasword { get; set; }
        public bool User_Active { get; set; }
        public string User_StartDate { get; set; }
        public Nullable<bool> User_Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Customers> Table_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Inventory> Table_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Invoice> Table_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Product> Table_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_ProductPriceManagment> Table_ProductPriceManagment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_UserLog> Table_UserLog { get; set; }
    }
}
