//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Invoice()
        {
            this.Table_InvoiceProduct = new HashSet<Table_InvoiceProduct>();
        }
    
        public int Invoice_ID { get; set; }
        public string Invoice_DateTime { get; set; }
        public Nullable<long> Invoice_Price { get; set; }
        public Nullable<long> Invoice_BuyingPrice { get; set; }
        public string Invoice_Description { get; set; }
        public Nullable<bool> Invoice_Type { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Table_Customers Table_Customers { get; set; }
        public virtual Table_Users Table_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_InvoiceProduct> Table_InvoiceProduct { get; set; }
    }
}
