//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_UserLog
    {
        public long UserLog_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string UserLog_CompuerName { get; set; }
        public string UserLog_IPAddress { get; set; }
        public string UserLog_IPV6Address { get; set; }
        public string UserLog_EnterDate { get; set; }
        public string UserLog_ExitDate { get; set; }
    
        public virtual Table_Users Table_Users { get; set; }
    }
}
