//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Product()
        {
            this.Table_Inventory = new HashSet<Table_Inventory>();
            this.Table_InvoiceProduct = new HashSet<Table_InvoiceProduct>();
            this.Table_ProductPriceManagment = new HashSet<Table_ProductPriceManagment>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Discription { get; set; }
        public Nullable<long> Product_LastPrice { get; set; }
        public Nullable<long> Product_LastBuyingPrice { get; set; }
        public Nullable<int> Product_LastInventory { get; set; }
        public byte[] Product_Image { get; set; }
        public string Product_RegisterDate { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<bool> Product_Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Inventory> Table_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_InvoiceProduct> Table_InvoiceProduct { get; set; }
        public virtual Table_Users Table_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_ProductPriceManagment> Table_ProductPriceManagment { get; set; }
    }
}
