//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_View
    {
        public int User_ID { get; set; }
        public string User_FullName { get; set; }
        public string User_Tel { get; set; }
        public Nullable<byte> User_Age { get; set; }
        public string User_Gender { get; set; }
        public string User_Active { get; set; }
        public string User_FirstName { get; set; }
        public string User_LastName { get; set; }
        public string User_Username { get; set; }
        public string User_StartDate { get; set; }
        public Nullable<bool> User_Delete { get; set; }
    }
}
