//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customer
    {
        public int Customer_ID { get; set; }
        public string Customer_FullName { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_PhoneNumber { get; set; }
        public string Customer_RegisterDate { get; set; }
        public string Register_User { get; set; }
        public Nullable<bool> Customer_Delete { get; set; }
    }
}
