//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Product
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<long> Product_LastPrice { get; set; }
        public Nullable<long> Product_LastBuyingPrice { get; set; }
        public Nullable<int> Product_LastInventory { get; set; }
        public byte[] Product_Image { get; set; }
        public string Product_Discription { get; set; }
        public string Product_RegisterDate { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Register_User { get; set; }
        public string User_FirstName { get; set; }
        public string User_LastName { get; set; }
        public Nullable<bool> Product_Delete { get; set; }
    }
}
