//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Inventory
    {
        public int Inventory_ID { get; set; }
        public long Inventory_Count { get; set; }
        public string Inventory_Date { get; set; }
        public string Inventory_Description { get; set; }
        public int User_ID { get; set; }
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Register_User { get; set; }
        public string InventoryCountStatus { get; set; }
    }
}
